server:
  port: 8080
  servlet:
    context-path: /api

mybatis:
  type-handlers-package: com.dovydasvenckus.timetracker.config.persistence.typehandlers
  configuration:
    map-underscore-to-camel-case: true

pagination:
  defaultSize: 20