server:
  port: 8180

spring:
  datasource:
    url: jdbc:postgresql://localhost/time_tracker
    username: time_tracker
    password: super-secret-pass

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091