server:
  port: 8080
  servlet:
    context-path: /api

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091
  jpa:
    hibernate:
      ddl-auto: validate

pagination:
  defaultSize: 20