version: "3.7"
services:
  time-tracker-db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=time_tracker
      - POSTGRES_PASSWORD=super-secret-pass
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  authorization-server:
    image: authelia/authelia:4
    network_mode: "host"
    volumes:
      - ./authelia:/config